spring:
  # Application
  application:
    name: myschool
  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/myschool_db
    username: myschool
    password: passwordForMyschool
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# Server
server:
  port: 8080